### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wasade** [DisruptiveLabs/sqlalchemy_postgresql_json#5]
I'm looking to use sqlalchemy with ltree, and suspect this code will do the trick. However, I'm hesitant to use or experiment with the code as there isn't a license associated with the repository. Would the authors consider licensing this code under BSD or something as or more permissive?

**Comment by kageurufu** [comment]
Daniel,

I'll add the MIT license later today, feel free to use it!

**Comment by wasade** [comment]
Great, thank you!

**Comment by kageurufu** [comment]
Fixed! enjoy!
